# use Dockerfile and than mount this root as volume
version: '3.8'
services:
  builder-ubuntu-22.04:
    build:
      context: .
      dockerfile: packaging/ubuntu22.dockerfile
    volumes:
      - ./packaging/output:/data
    environment:
      - VERSION=1.0.0
      - PREFIX=ubuntu22

  builder-debian-11:
    build:
      context: .
      dockerfile: packaging/debian11.dockerfile
    volumes:
      - ./packaging/output:/data
    environment:
      - VERSION=1.0.0
      - PREFIX=debian11

  builder-fedora-41:
    build:
      context: .
      dockerfile: packaging/fedora41.dockerfile
    volumes:
      - ./packaging/output:/data
    environment:
      - VERSION=1.0.0
      - PREFIX=fedora41
