name: Linux Debian Packaging

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - "dev-build"
      version:
        required: true
        type: choice
        options:
          - "1.0.0"

jobs:
  package:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    container: "debian:13"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Setup dependencies
        run: |
          apt-get -q update && apt-get -q upgrade -y
          apt-get -q install -y wget git gpg

          wget https://download.bell-sw.com/java/25.0.4+9/bellsoft-jdk25.0.4+9-linux-amd64-full.deb
          apt-get -q install -y ./bellsoft-jdk25.0.4+9-linux-amd64-full.deb
          apt-get -q install -y binutils fakeroot

      - uses: actions/checkout@v4

      - name: Build artifact
        run: |
          export JAVA_HOME=/usr/lib/jvm/$(ls /usr/lib/jvm/ | grep bellsoft-java25-full)
          export PATH=$JAVA_HOME/bin:$PATH

          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          ./mvnw versions:set -DnewVersion=${VERSION}

          ./mvnw -B -C -V package -P system-jdk
          ls -lah ./target

      - name: Rename artifact
        run: |
          mv target/autogram*.deb target/autogram-${VERSION}-debian.deb

      - name: Upload artifact
        if: ${{ inputs.environment == 'dev-build' }}
        uses: actions/upload-artifact@v6
        with:
          name: autogram-${{ inputs.version }}-debian.deb
          path: target/autogram-${{ inputs.version }}-debian.deb
          if-no-files-found: ignore

      - name: Create release if tag pushed
        if: ${{ inputs.environment == 'packaging' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          draft: true
          prerelease: true
          files: |
            target/autogram-${{ inputs.version }}-debian.deb
